global:
  scrape_interval: 1s
  scrape_timeout: 1s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'idonotexists:564'
          - 'helloworld:9090'
          - 'localhost:9090'
          - 'localhost:8080'
          - 'activemq:8080'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093