version: '3'

services:

  activemq:
    image: bwolf/activemq-prometheus
    ports:
    - published: 61616
      target: 61616
    - published: 61613
      target: 61613
    - published: 8161
      target: 8161
    - published: 8080
      target: 8080
    restart: unless-stopped
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - "${PGADMIN_LISTEN_PORT}:5050"

  script-db:
    image: postgres:13-alpine
    container_name: script-db
    ports:
      - "${SCRIPT_DATABASE_PORT}:${SCRIPT_DATABASE_PORT}"
    command: -p ${SCRIPT_DATABASE_PORT}
    environment:
      - DEBUG=false
      - POSTGRES_USER=${SCRIPT_USER_NAME}
      - POSTGRES_PASSWORD=${SCRIPT_USER_PASSWORD}
      - POSTGRES_DB=${SCRIPT_DATABASE_NAME}
    volumes:
      - script-db:/var/lib/postgresql/data
    restart: unless-stopped

  consumer-db:
    image: postgres:13-alpine
    container_name: consumer-db
    ports:
      - "9292:9292"
    command: -p 9292
    environment:
      - DEBUG=false
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=consumer-db
    volumes:
      - consumer-db:/var/lib/postgresql/data
    restart: unless-stopped

  history-db:
    image: postgres:13-alpine
    container_name: history-db
    ports:
      - "${SUPPLIER_DATABASE_PORT}:${SUPPLIER_DATABASE_PORT}"
    command: -p ${SUPPLIER_DATABASE_PORT}
    environment:
      - DEBUG=false
      - POSTGRES_USER=${SUPPLIER_USER_NAME}
      - POSTGRES_PASSWORD=${SUPPLIER_USER_PASSWORD}
      - POSTGRES_DB=${SUPPLIER_DATABASE_NAME}
    volumes:
      - history-db:/var/lib/postgresql/data
    restart: unless-stopped

  spring-db:
    image: postgres:13-alpine
    container_name: spring-db
    ports:
      - "${SPRING_DATABASE_PORT}:${SPRING_DATABASE_PORT}"
    command: -p ${SPRING_DATABASE_PORT}
    environment:
      - DEBUG=false
      - POSTGRES_USER=${SPRING_USER_NAME}
      - POSTGRES_PASSWORD=${SPRING_USER_PASSWORD}
      - POSTGRES_DB=spring-db
    volumes:
      - spring-db:/var/lib/postgresql/data
    restart: unless-stopped
    
  prometheus:
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    deploy:
      replicas: 1
    image: prom/prometheus:v2.21.0
    ports:
    - published: 9000
      target: 9090
    volumes:
    - /mnt/c/Users/silas/Documents/Studium/8.Semester/bsc_thesis/thesis/nodejs-projects/autoscale/clean6/stack-scale-benchmark/stack/data/prometheus:/etc/prometheus:rw
    - prometheus-data:/prometheus:rw

  node-consumer:
    image: node-consumer:latest
    container_name: node-consumer
    build: node-consumer/
    depends_on:
      - activemq
      - script-db
    restart: unless-stopped
    environment: 
      - PG_HOSTNAME=script-db
      - AMQ_BROKER_HOSTNAME=activemq
      - PG_DATABASE_NAME=${SCRIPT_DATABASE_NAME}
      - PG_DATABASE_PORT=${SCRIPT_DATABASE_PORT}
      - PG_USER_NAME=${SCRIPT_USER_NAME}
      - PG_USER_PASSWORD=${SCRIPT_USER_PASSWORD}
      - AMQ_BROKER_PORT=${AMQ_STOMP_PORT}
      - AMQ_QUEUE_NAME=${AMQ_QUEUE_NAME}

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD="admin"
      - GF_SECURITY_ADMIN_USER="admin"


volumes:
  script-db:
  history-db:
  spring-db:
  consumer-db:
  prometheus-data:
